### ISSUE TITLE
Kitsune Mask_26404 version cannot be installed.

### ISSUE THREAD

**Issue by ssr123456789** [Zenlua/Overlayfs#16]
![Screenshot_2024-01-11-18-25-47-83_d2b75a1e572092fe23d5ff5ef04b7792](https://github.com/Zenlua/Overlayfs/assets/22828676/ed18cc4d-be9f-46cb-954a-c49ac5256962)

log：
[488000410_magisk_install_log_2024-01-10T09.01.22.log](https://github.com/Zenlua/Overlayfs/files/13901817/488000410_magisk_install_log_2024-01-10T09.01.22.log)

**Comment by Zenlua** [comment]
Tell them to update like the original magisk canary, because they mod to the kitsune version of magisk may not be the same as the original magisk canary version

**Comment by tinbilly** [comment]
Installation also failed on Magisk Alpha version a0b8aa4d-alpha-2 (26404).

**Comment by Zenlua** [comment]
Maybe your device or kernel does not support overlayfs

**Comment by tinbilly** [comment]
Strange. On that same device, I switched to APatch and the installation went well. But it kept the [GmsCore](https://github.com/microg/GmsCore) and real Google Play Store not working. If I disable the module, everything is back to normal.

**Comment by Zenlua** [comment]
Completely fixed.
