### ISSUE TITLE
module can cause baseband loss

### ISSUE THREAD

**Issue by xingluo233** [Zenlua/Overlayfs#17]
![Screenshot_2024-01-19-08-04-37-368_com.android.settings.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/8acbc955-3ae7-4568-9195-f8e6cac5ef10)

**Comment by Zenlua** [comment]
Try changing the mode in module.prop

vipmount=1

vipmount=2

Try both of these modes

**Comment by xingluo233** [comment]
> Try changing the mode in module.prop
> 
> vipmount=1
> 
> vipmount=2
> 
> Try both of these modes

Thanks, the baseband is back to normal after vipmount is changed to 2
