### ISSUE TITLE
After updating to version 1.3, the full mount failed

### ISSUE THREAD

**Issue by xingluo233** [Zenlua/Overlayfs#18]
![Screenshot_2024-01-20-01-08-00-945_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/fcbff191-4c83-4d79-8a17-3a16635fdeb0)

![Screenshot_2024-01-20-01-06-47-430_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/598739be-0592-4cfa-ae2a-eec14b02172c)

**Comment by Zenlua** [comment]
Do you use magisk, ksu?

**Comment by Zenlua** [comment]
Maybe redownload version 1.3 and reinstall it has changed a bit

**Comment by xingluo233** [comment]
> Maybe redownload version 1.3 and reinstall it has changed a bit 

I'm using APatch and reinstalling doesn't help!

**Comment by Zenlua** [comment]
> > Maybe redownload version 1.3 and reinstall it has changed a bit
> 
> I'm using APatch and reinstalling doesn't help!

Reinstall 1.3 and try 2 modes in module.prop

**Comment by Zenlua** [comment]
vipmodun=1
vipmodun=2

Previous version mode was 2, try number 1

**Comment by xingluo233** [comment]
> vipmodun=1
> vipmodun=2
> 
> Previous version mode was 2, try number 1

Whether is changed to 1 or 2, it still fails to mount

**Comment by xingluo233** [comment]
In version 1.2, vipmount=2 is normal

**Comment by Zenlua** [comment]
All problems resolved

**Comment by xingluo233** [comment]
> All problems resolved 

It still fails to mount, even the log.txt file doesn't exist anymore

**Comment by Zenlua** [comment]
> > All problems resolved
> 
> It still fails to mount, even the log.txt file doesn't exist anymore

Fixd

**Comment by xingluo233** [comment]
> > > All problems resolved
> > 
> > It still fails to mount, even the log.txt file doesn't exist anymore
> 
> Fixd

Invalid argument
![Screenshot_2024-01-21-17-40-10-760_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/75d3893b-5b98-4df6-9e48-d89ebeee31c4)

**Comment by Zenlua** [comment]
Turn off all modules, only turn on my module. And reinstall.

Or uninstall the module and reinstall it.

**Comment by xingluo233** [comment]
> Turn off all modules, only turn on my module. And reinstall.
> 
> Or uninstall the module and reinstall it.

I uninstalled all modules and reinstalled overlayfs, still Invalid argument
![Screenshot_2024-01-22-07-31-56-719_me.bmax.apatch.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/d737f8b7-b1a0-4783-a46d-77011053ad3a)

![Screenshot_2024-01-22-07-31-46-561_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/9834a348-e5e7-4b9f-a400-272d2f88130b)

**Comment by xingluo233** [comment]
@Zenlua I used magisk and still get Invalid argument
![Screenshot_2024-01-25-15-32-30-672_z.xzm.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/6ecd8293-9d1d-4c85-bd81-4c399a7972b4)

![Screenshot_2024-01-25-15-34-37-065_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/15ad59de-7f4d-48ec-8bb9-46f1138b37b6)

**Comment by xingluo233** [comment]
vipmount=1
![Screenshot_2024-01-25-16-03-02-241_bin.mt.plus.canary.jpg](https://github.com/Zenlua/Overlayfs/assets/54618947/eb1bf9f9-c567-4a73-bb45-05ee70a09970)

**Comment by xingluo233** [comment]
After updating to version 135, vipmount=1 will not report not found, but vipmount=1 and vipmount=2 will still report Invalid argument.
