### ISSUE TITLE
[Feature Addition] Additional Paths You May Consider Adding

### ISSUE THREAD

**Issue by adrianmmiller** [Zenlua/Overlayfs#19]
I added these to some of my magisk modules that deal with system files, notably my GMS Doze custom module one as some vendors have relevant files in these Vendor/OEM folders

/india (some vendors in India)
/my_bigball (OnePlus)

**Comment by Zenlua** [comment]
/data/overlayfs/tmp/overlayrw

Read this command in the main section
It will be added even if updated without losing it.

**Comment by Zenlua** [comment]
https://github.com/Zenlua/Overlayfs#overlayfs-rw

**Comment by Zenlua** [comment]
Or add the path here /data/overlayfs/tmp/path

**Comment by adrianmmiller** [comment]
> https://github.com/Zenlua/Overlayfs#overlayfs-rw

sorry i meant for possible addition in https://github.com/Zenlua/Overlayfs/blob/main/module/common/partition

as i thought that was maybe a common list of paths?  maybe im not reading this correctly however

**Comment by Zenlua** [comment]
Sorry, I can't add because so many devices, have their own folder.
